In [1]:
from bs4 import BeautifulSoup
import requests
from selenium import webdriver
from selenium.webdriver.common.keys import Keys
import time
import pandas as pd
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import statsmodels.api as sm
%config InlineBackend.figure_formats = ['svg']
from mpl_toolkits.mplot3d import Axes3D
%matplotlib inline

sns.set(context='notebook', style='whitegrid', font_scale=1.2)

In [2]:
bball_ref_team_abbrv = {
    'ARI': 'Arizona Diamondbacks',
    'ATL': 'Atlanta Braves',
    'BAL': 'Baltimore Orioles',
    'BOS': 'Boston Red Sox',
    'CHC': 'Chicago Cubs',
    'CHW': 'Chicago White Sox',
    'CIN': 'Cincinnati Reds',
    'CLE': 'Cleveland Indians',
    'COL': 'Colorado Rockies',
    'DET': 'Detroit Tigers',
    'HOU': 'Houston Astros',
    'KCR': 'Kansas City Royals',
    'ANA': 'Los Angeles Angels',
    'LAD': 'Los Angeles Dodgers',
    'FLA': 'Miami Marlins',
    'MIL': 'Milwaukee Brewers',
    'MIN': 'Minnesota Twins',
    'NYM': 'New York Mets',
    'NYY': 'New York Yankees',
    'OAK': 'Oakland Athletics',
    'PHI': 'Philadelphia Phillies',
    'PIT': 'Pittsburgh Pirates',
    'SDP': 'San Diego Padres',
    'SFG': 'San Francisco Giants',
    'SEA': 'Seattle Mariners',
    'STL': 'St. Louis Cardinals',
    'TBD': 'Tampa Bay Rays',
    'TEX': 'Texas Rangers',
    'TOR': 'Toronto Blue Jays',
    'WSN': 'Washington Nationals'
    
}

offensive_stat_header = ['Year', 'Team', 'Lg', 'W', 'L', 'Finish', 'G', 'PA', 'AB', 'R', 'H', '2B', '3B', 'HR',
                         'RBI', 'SB', 'CS', 'BB', 'SO', 'BA', 'OBP', 'SLG', 'OPS', 'E', 'DP', 'Fld%']

pitching_stat_header = ["Year", 'Team', "Lg", "W", "L", "Finish", "RA/G", "ERA", "G", "CG", "tSho", "SV", "IP", "H_A", "R_A", "ER", "HRA", 
                        "BB_A", "SO_A", "WHIP", "SO9", "HR9", "E_P", "DP_P", "Fld%_P", "PAge"]

# Practice on the Giants Page

In [ ]:
# set the url for the SF Giants batters
url = 'https://www.baseball-reference.com/teams/SFG/batteam.shtml'

In [ ]:
# grab and check the response
response = requests.get(url)
response.status_code

In [ ]:
page = response.text
type(page)

In [ ]:
soup = BeautifulSoup(page, "lxml")

In [ ]:
# data is produced dynaically... need to use driver and selenium
batter_stats_table = soup.find_all(id='div_yby_team_bat_per_game')
batter_stats_table

In [ ]:
# set the path and the driver 
PATH="/Applications/chromedriver"
driver = webdriver.Chrome(PATH)

In [ ]:
# have the driver grab the url
driver.get("https://www.baseball-reference.com/teams/SFG/batteam.shtml")

html = driver.page_source
soup = BeautifulSoup(html)

# now the table has data
batter_stats_table = soup.find(id='div_yby_team_bat_per_game');

In [ ]:
# grab all the rows and put the data in a season list
headers = batter_stats_table.find('thead').find_all('th')
header = [h.text for h in headers]
rows = batter_stats_table.find('tbody').find_all('tr')
seasons_list = []
for r in rows:
    year = r.find('th').text
    if year.isdigit() and int(year) > 1950:
        data = r.find_all('td')
        season_stats=[d.text for d in data]
        season_stats = [year] + ['SFG'] + season_stats
        seasons_list.append(season_stats)

In [ ]:
driver.close()

In [ ]:
# it looks good, lets make this a function
pd.DataFrame(seasons_list)

# Take what we did above and put it in a function and grab all teams

In [ ]:
def scrape_team_batting_data(team, driver):
    # have the driver grab the url
    url = "https://www.baseball-reference.com/teams/{}/batteam.shtml".format(team)
    driver.get(url)
    html = driver.page_source
    soup = BeautifulSoup(html)
    
    # grab the table we want (stats per game by year)
    batter_stats_table = soup.find(id='div_yby_team_bat_per_game');
    
    # grab all the rows and put the data in a season list
    rows = batter_stats_table.find('tbody').find_all('tr')
    seasons_list = []
    for r in rows:
        year = r.find('th').text
        if year.isdigit() and int(year) >= 1950:
            data = r.find_all('td')
            season_stats=[d.text for d in data]
            season_stats = [year] + [team] + season_stats
            seasons_list.append(season_stats)
            
    return(seasons_list)

In [ ]:
def scrape_team_pitching_data(team, driver):
    # have the driver grab the url
    url = "https://www.baseball-reference.com/teams/{}/pitchteam.shtml".format(team)
    driver.get(url)
    html = driver.page_source
    soup = BeautifulSoup(html)
    
    # grab the table we want (stats per game by year)
    pitcher_stats_table = soup.find(id='div_yby_team_pitch_per_game');
    
    # grab all the rows and put the data in a season list
    rows = pitcher_stats_table.find('tbody').find_all('tr')
    seasons_list = []
    for r in rows:
        year = r.find('th').text
        if year.isdigit() and int(year) >= 1950:
            data = r.find_all('td')
            season_stats=[d.text for d in data]
            season_stats = [year] + [team] + season_stats
            seasons_list.append(season_stats)
            
    return(seasons_list)

In [ ]:
"""
# run it on the SFG page
PATH="/Applications/chromedriver"
driver = webdriver.Chrome(PATH)

url = "SFG"

team_batting_data = scrape_team_batting_data(url, driver)

driver.close()

# it works
"""

In [ ]:
teams = list(bball_ref_team_abbrv.keys())

In [ ]:
PATH="/Applications/chromedriver"
driver = webdriver.Chrome(PATH)
all_batting_data = []
all_pitching_data = []
for t in teams:
    print(t)
    team_batting_data = scrape_team_batting_data(t, driver)
    all_batting_data = all_batting_data + team_batting_data
    
    team_pitching_data = scrape_team_pitching_data(t, driver)
    all_pitching_data = all_pitching_data + team_pitching_data
    
    
driver.close()

In [ ]:
# add the header 
all_batting_data.insert(0, offensive_stat_header)
all_batting_data

In [ ]:
# add the header 
all_pitching_data.insert(0, pitching_stat_header)
all_pitching_data

In [ ]:
# create data frame
all_batting_df = pd.DataFrame(all_batting_data[1:],columns=all_batting_data[0])
all_pitching_df = pd.DataFrame(all_pitching_data[1:],columns=all_pitching_data[0])

In [ ]:
len(all_pitching_df.index), len(all_batting_df.index)

In [ ]:
for c in all_batting_df.columns:
    try:
        all_batting_df[c] = pd.to_numeric(all_batting_df[c])
    except:
        pass

In [ ]:
for c in all_pitching_df.columns:
    try:
        all_pitching_df[c] = pd.to_numeric(all_pitching_df[c])
    except:
        pass

In [ ]:
all_pitching_df.columns = pitching_stat_header

In [ ]:
# pickle this so we dont need to redo
all_batting_df.to_pickle("full_batting_from_1950_df.pkl")
all_pitching_df.to_pickle("full_batting_from_1950_df.pkl")

In [ ]:
full_baseball_df = pd.merge(all_batting_df, all_pitching_df.drop(columns=["Lg", "W", "L", "Finish","G"]), on=['Year', 'Team'])

In [ ]:
full_baseball_df.head()

In [ ]:
full_baseball_df.to_pickle("full_baseball_from_1950_df.pkl")

# Grab Opponent against stats

In [3]:
url = "https://www.baseball-reference.com/leagues/MLB/2020-batting-pitching.shtml"

In [33]:
def scrape_opponent_batting(year, driver):
    # have the driver grab the url
    print(year)
    url = "https://www.baseball-reference.com/leagues/MLB/{}-batting-pitching.shtml".format(str(year))
    driver.get(url)
    time.sleep(0.5)
    html = driver.page_source
    soup = BeautifulSoup(html)

    # now the table has data
    stats_table = soup.find(id='teams_batting_pitching');
    rows = stats_table.find('tbody').find_all('tr')
    all_teams = []
    for r in rows:
        team = r.find('th').text
        if team != 'LgAvg':
            data = r.find_all('td')
            team_stats=[d.text for d in data]
            team_stats = [year] + [team] + team_stats
            all_teams.append(team_stats)
    return(all_teams)

In [34]:
"""
# set the path and the driver 
PATH="/Applications/chromedriver"
driver = webdriver.Chrome(PATH)
opponents_2020 = scrape_opponent_batting(2020, driver)
driver.close()
""";

In [36]:
PATH="/Applications/chromedriver"
driver = webdriver.Chrome(PATH)
full_list = []
for i in range(1950, 2021):
    opponents_yearly = scrape_opponent_batting(i, driver)  
    full_list = full_list + opponents_yearly
    
driver.close()

1950
1951
1952
1953
1954
1955
1956
1957
1958
1959
1960
1961
1962
1963
1964
1965
1966
1967
1968
1969
1970
1971
1972
1973
1974
1975
1976
1977
1978
1979
1980
1981
1982
1983
1984
1985
1986
1987
1988
1989
1990
1991
1992
1993
1994
1995
1996
1997
1998
1999
2000
2001
2002
2003
2004
2005
2006
2007
2008
2009
2010
2011
2012
2013
2014
2015
2016
2017
2018
2019
2020

In [37]:
opponent_headers = ["Year", "Team", "RA/G", "PAu", "G", "PA", "AB", "R", "H", "2B", "3B", "HR", "SB", 
                    "CS", "BB", "SO", "BA", "OBP", "SLG", "OPS", "BAbip", "TB", "GDP", "HBP", "SH", 
                    "SF", "IBB", "ROE"]

In [47]:
opponents_df = pd.DataFrame(full_list,columns=opponent_headers)
opponents_df

,Year,Team,RA/G,PAu,G,PA,AB,R,H,2B,...,SLG,OPS,BAbip,TB,GDP,HBP,SH,SF,IBB,ROE
0,1950,BOS,5.22,615,154,6086,5224,804,1413,218,...,.400,.765,.289,2092,136,23,90,0,0,56
1,1950,BRO,4.67,3,155,5996,5336,724,1397,223,...,.410,.748,.280,2187,150,21,46,0,0,65
2,1950,BSN,4.72,824,156,6024,5365,736,1411,212,...,.387,.722,.277,2074,107,30,75,0,0,81
3,1950,CHC,5.01,788,154,6061,5364,772,1452,251,...,.402,.748,.283,2155,110,27,76,0,0,106
4,1950,CHW,4.80,1287,156,6058,5215,749,1370,193,...,.374,.729,.278,1948,119,21,88,0,0,62
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1767,2020,STL,3.95,,58,1989,1739,229,376,70,...,.380,.686,.252,661,41,26,3,14,8,19
1768,2020,TBR,3.82,,60,2212,1995,229,475,83,...,.391,.696,.293,780,43,29,9,10,4,15
1769,2020,TEX,5.20,,60,2273,1981,312,479,83,...,.419,.749,.279,831,34,30,8,17,3,21
1770,2020,TOR,5.20,,60,2309,2027,312,517,105,...,.436,.775,.303,883,42,14,6,12,7,18
1771,2020,WSN,5.02,,60,2273,2025,301,548,101,...,.466,.812,.317,943,40,22,3,7,22,24

In [49]:
opponents_df.Team.unique()

array(['BOS', 'BRO', 'BSN', 'CHC', 'CHW', 'CIN', 'CLE', 'DET', 'NYG',
       'NYY', 'PHA', 'PHI', 'PIT', 'SLB', 'STL', 'WSH', 'MLN', 'BAL',
       'KCA', 'LAD', 'SFG', 'LAA', 'MIN', 'WSA', 'HOU', 'NYM', 'CAL',
       'ATL', 'OAK', 'KCR', 'MON', 'SDP', 'SEP', 'MIL', 'TEX', 'SEA',
       'TOR', 'COL', 'FLA', 'ANA', 'ARI', 'TBD', 'WSN', 'TBR', 'MIA'],
      dtype=object)

In [50]:
bball_ref_team_abbrv_convert = {
    'MLN': 'ATL',
    'BRO': 'LAD',
    'BSN': 'ATL',
    'NYG': 'SFG',
    'PHA': 'OAK',
    'SLB': 'BAL',
    'KCA': 'OAK',
    'WSA': 'TEX',
    'CAL': 'ANA',
    'MON': 'WSN',
    'SEP': 'MIL',
    'LAA': 'ANA',
    'WSH': 'MIN',
    'TBR': 'TBD',
    'MIA': 'FLA',
    'ARI': 'ARI',
    'ATL': 'ATL',
    'BAL': 'BAL',
    'BOS': 'BOS',
    'CHC': 'CHC',
    'CHW': 'CHW',
    'CIN': 'CIN',
    'CLE': 'CLE',
    'COL': 'COL',
    'DET': 'DET',
    'HOU': 'HOU',
    'KCR': 'KCR',
    'ANA': 'ANA',
    'LAD': 'LAD',
    'FLA': 'FLA',
    'MIL': 'MIL',
    'MIN': 'MIN',
    'NYM': 'NYM',
    'NYY': 'NYY',
    'OAK': 'OAK',
    'PHI': 'PHI',
    'PIT': 'PIT',
    'SDP': 'SDP',
    'SFG': 'SFG',
    'SEA': 'SEA',
    'STL': 'STL',
    'TBD': 'TBD',
    'TEX': 'TEX',
    'TOR': 'TOR',
    'WSN': 'WSN',
}

In [51]:
opponents_df.Team = opponents_df.Team.map(bball_ref_team_abbrv_convert, na_action='ignore')

In [52]:
opponents_df.Team.unique()

array(['BOS', 'LAD', 'ATL', 'CHC', 'CHW', 'CIN', 'CLE', 'DET', 'SFG',
       'NYY', 'OAK', 'PHI', 'PIT', 'BAL', 'STL', 'MIN', 'ANA', 'TEX',
       'HOU', 'NYM', 'KCR', 'WSN', 'SDP', 'MIL', 'SEA', 'TOR', 'COL',
       'FLA', 'ARI', 'TBD'], dtype=object)

In [53]:
for c in opponents_df.columns:
    try:
        opponents_df[c] = pd.to_numeric(opponents_df[c])
    except:
        pass

In [54]:
opponents_df.to_pickle("opponents_from_1950_df.pkl")